package javaweb.Entity;
// Generated Jul 1, 2021, 2:48:58 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BillHasProductHasSizeId generated by hbm2java
 */
@Embeddable
public class BillHasProductHasSizeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int billId;
	private int productHasSizeProductId;
	private int productHasSizeSizeId;

	public BillHasProductHasSizeId() {
	}

	public BillHasProductHasSizeId(int billId, int productHasSizeProductId, int productHasSizeSizeId) {
		this.billId = billId;
		this.productHasSizeProductId = productHasSizeProductId;
		this.productHasSizeSizeId = productHasSizeSizeId;
	}

	@Column(name = "BILL_ID", nullable = false)
	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	@Column(name = "PRODUCT_has_SIZE_PRODUCT_ID", nullable = false)
	public int getProductHasSizeProductId() {
		return this.productHasSizeProductId;
	}

	public void setProductHasSizeProductId(int productHasSizeProductId) {
		this.productHasSizeProductId = productHasSizeProductId;
	}

	@Column(name = "PRODUCT_has_SIZE_SIZE_ID", nullable = false)
	public int getProductHasSizeSizeId() {
		return this.productHasSizeSizeId;
	}

	public void setProductHasSizeSizeId(int productHasSizeSizeId) {
		this.productHasSizeSizeId = productHasSizeSizeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillHasProductHasSizeId))
			return false;
		BillHasProductHasSizeId castOther = (BillHasProductHasSizeId) other;

		return (this.getBillId() == castOther.getBillId())
				&& (this.getProductHasSizeProductId() == castOther.getProductHasSizeProductId())
				&& (this.getProductHasSizeSizeId() == castOther.getProductHasSizeSizeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBillId();
		result = 37 * result + this.getProductHasSizeProductId();
		result = 37 * result + this.getProductHasSizeSizeId();
		return result;
	}

}
