package javaweb.Entity;
// Generated Jul 1, 2021, 2:48:58 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductHasSize generated by hbm2java
 */
@Entity
@Table(name = "product_has_size", catalog = "phonedata")
public class ProductHasSize implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProductHasSizeId id;
	private Product product;
	private Size size;
	private Integer amount;
	private Set<BillHasProductHasSize> billHasProductHasSizes = new HashSet<BillHasProductHasSize>(0);

	public ProductHasSize() {
	}

	public ProductHasSize(ProductHasSizeId id, Product product, Size size) {
		this.id = id;
		this.product = product;
		this.size = size;
	}

	public ProductHasSize(ProductHasSizeId id, Product product, Size size, Integer amount,
			Set<BillHasProductHasSize> billHasProductHasSizes) {
		this.id = id;
		this.product = product;
		this.size = size;
		this.amount = amount;
		this.billHasProductHasSizes = billHasProductHasSizes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false)),
			@AttributeOverride(name = "sizeId", column = @Column(name = "SIZE_ID", nullable = false)) })
	public ProductHasSizeId getId() {
		return this.id;
	}

	public void setId(ProductHasSizeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIZE_ID", nullable = false, insertable = false, updatable = false)
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "AMOUNT")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productHasSize")
	public Set<BillHasProductHasSize> getBillHasProductHasSizes() {
		return this.billHasProductHasSizes;
	}

	public void setBillHasProductHasSizes(Set<BillHasProductHasSize> billHasProductHasSizes) {
		this.billHasProductHasSizes = billHasProductHasSizes;
	}

}
