package javaweb.Entity;
// Generated Jul 1, 2021, 2:48:58 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Size generated by hbm2java
 */
@Entity
@Table(name = "size", catalog = "phonedata")
public class Size implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Set<ProductHasSize> productHasSizes = new HashSet<ProductHasSize>(0);

	public Size() {
	}

	public Size(String name) {
		this.name = name;
	}

	public Size(String name, Set<ProductHasSize> productHasSizes) {
		this.name = name;
		this.productHasSizes = productHasSizes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "size")
	public Set<ProductHasSize> getProductHasSizes() {
		return this.productHasSizes;
	}

	public void setProductHasSizes(Set<ProductHasSize> productHasSizes) {
		this.productHasSizes = productHasSizes;
	}

}
